### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by MiChatz** [keshavbhatt/orange#2]
Unfortunately is not working in my case.    
I have installed it via the command line 
```
sudo snap install orange-app
```
after running the orange-app I have the following error.
```
Gtk-Message: 13:42:15.724: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:42:15.725: Failed to load module "canberra-gtk-module"
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Fontconfig warning: FcPattern object weight does not accept value [40 210)
Segmentation fault (core dumped)

```

**Comment by keshavbhatt** [comment]
OS you using ?

**Comment by keshavbhatt** [comment]
This doesn't happen on my system. Please open a thread at https://forum.snapcraft.io so more users can test and confirm.

**Comment by MiChatz** [comment]
I am using Ubuntu 20.04

**Comment by keshavbhatt** [comment]
this seem similar to https://github.com/keshavbhatt/red/issues/1

**Comment by Kaydax** [comment]
even after trying everything described in https://github.com/keshavbhatt/red/issues/1, it still throws the same error. I'm running Manjaro Linux 21.1.6 with KDE (Linux Kernel 5.13.19)

**Comment by keshavbhatt** [comment]
https://github.com/keshavbhatt/red/issues/1#issuecomment-846354883 This worked for many people.

**Comment by Kaydax** [comment]
> [keshavbhatt/red#1 (comment)](https://github.com/keshavbhatt/red/issues/1#issuecomment-846354883) This worked for many people.

Yah but I have tried this multiple times, even with rebooting, and i still received the same error
