### ISSUE TITLE
Is it possible to use this on windows ?

### ISSUE THREAD

**Issue by Lucaspec72** [keshavbhatt/orange#3]
I love using this on linux and would like to also use it on windows, but it seems WSL really doesn't like it when i try to run orange. is there a way i can use this on windows with WSL somehow ? (A̶ ̶w̶i̶n̶d̶o̶w̶s̶ ̶v̶e̶r̶s̶i̶o̶n̶ ̶w̶o̶u̶l̶d̶ ̶b̶e̶ ̶p̶r̶e̶t̶t̶y̶ ̶n̶e̶a̶t̶,̶ ̶b̶u̶t̶ ̶i̶ ̶g̶u̶e̶s̶s̶ ̶p̶o̶r̶t̶i̶n̶g̶ ̶i̶t̶ ̶m̶a̶y̶ ̶n̶o̶t̶ ̶b̶e̶ ̶p̶o̶s̶s̶i̶b̶l̶e̶ just saw a port is planned on the readme)

**Comment by keshavbhatt** [comment]
No, not yet. Due to a very busy schedule, I am not able to put my efforts into porting this app for windows yet. Any future updates will fall on the ReadMe page of the project.
Thanks
