### ISSUE TITLE
Google login not working

### ISSUE THREAD

**Issue by Jnoack331** [keshavbhatt/orange#5]
Hi @keshavbhatt,

i have the following problem when loggin into my google account:
![Bildschirmfoto von 2021-03-22 10-07-08](https://user-images.githubusercontent.com/17640771/111966836-ad101680-8af7-11eb-8e75-adde85a6f38b.png)

Translates to: This browser is unsecure.

This thread could help:
https://support.google.com/accounts/thread/22873505?hl=en

I already tried enabling insecure apps in my google account with no luck.

**Comment by Jnoack331** [comment]
current workaround:

1. Login in a Browser
2. goto https://soundcloud.com/settings
3. reset password
4. now you can access the soundcloud account via google email + your newly set password

**Comment by keshavbhatt** [comment]
Thanks for reporting this issue, i will fix this soon.

**Comment by VotesNHose** [comment]
This issue should be reopened as it still exists and the workaround above no longer works
