### ISSUE TITLE
This is not opensource?

### ISSUE THREAD

**Issue by seppzer0** [keshavbhatt/orange#8]
Hi, first of all -- great app, very smooth compared to other solutions I found for Linux!

But I noticed that you don't really provide full sources, just a binary called "orange".
Honestly, this is a bit concerning -- why not provide sources to build that binary?

Could you share full sources used for the binary? 
Automated build scripts would be useful too, but not necessary as of right now.

**Comment by seppzer0** [comment]
Soo any comments on this??

**Comment by keshavbhatt** [comment]
Hi, Sorry for the late response.
No, its not Open source.

**Comment by keshavbhatt** [comment]
This repository is, just for issue tracking. I have automated pipelines in places that are delivering the builds via the store.
Thanks :)

**Comment by seppzer0** [comment]
Alright, got it.
I must admit, I really like this app, but unfortunately because it is not open source - I can't use it.
Would be awesome if you changed your mind and opened the source.

I am closing this issue.
